DROP TABLE IF EXISTS 'Korisnik';
CREATE TABLE IF NOT EXISTS 'Korisnik' (
'IdKor' INTEGER  NOT NULL,
'Ime' TEXT  NOT NULL,
'Prezime' TEXT  NOT NULL,
'Mejl' TEXT  NOT NULL,
'KorisnickoIme' TEXT  DEFAULT NULL,
'Lozinka' TEXT  DEFAULT NULL,
'Flag' tinyINTEGER NOT NULL DEFAULT '0',
PRIMARY KEY ('IdKor')
);